version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: some-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-initalize:
    build: ./DB
    container_name: db-initializer
    depends_on:
      - postgres
    env_file:
      - .env

  ui:
    build: ./UI
    container_name: dash-ui
    depends_on:
      - postgres
      - db-initalize
      - api
    ports:
      - "8050:8050"
    env_file:
      - .env
  api:
    build: ./API_fetcher  
    container_name: api-fetcher-service
    depends_on:
      - postgres
      - db-initalize
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  postgres_data: 
    driver: local