name: API Fetcher Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/API_fetcher/**'  
  pull_request:
    branches:
      - main 
    paths:
      - 'src/API_fetcher/**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./src/API_fetcher  
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./src/API_fetcher
      run: python -m unittest discover tests
